import type { Metadata } from "next";
import "./globals.css";
import { DarkModeToggle } from "../components/DarkModeToggle";
import { BingoProvider } from "@/context/BingoContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { body, nav, h1 } = layoutStyles;

  return (
    <html lang="en">
      <body className={body}>
        <nav className={nav}>
          <h1 className={h1}>City Stroll Bingo</h1>
          <DarkModeToggle />
        </nav>

        <BingoProvider>{children}</BingoProvider>
      </body>
    </html>
  );
}

const layoutStyles = {
  body: "bg-white dark:bg-gray-800 text-gray-800 dark:text-white",
  nav: "flex justify-between items-center p-4 bg-gray-100 dark:bg-gray-900",
  h1: "text-2xl font-bold",
};
